title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/S-B99/kamiblue
  website_url: https://github.com/S-B99/kamiblueWebsite
  zip_url: https://github.com/S-B99/kamiblueWebsite/zipball/master
  tar_url: https://github.com/S-B99/kamiblueWebsite/tarball/master
  jar_url: https://github.com/S-B99/kamiblue/releases/download/v1.1.2/KAMI-Blue-v1.1.2-release.jar
  beta_jar_url: https://cdn.discordapp.com/attachments/634549110145286156/684065785651527729/kblue-beta-v1.1.2-03-02-01-release.jar
discord_url: https://discord.gg/KfpqwZB
baritone_url: https://github.com/cabaletta/baritone/releases/tag/v1.2.10
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag